# Generated by Django 3.1.7 on 2021-02-26 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20210226_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_model',
        ),
    ]
