# Generated by Django 3.1.7 on 2021-02-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_remove_car_car_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='owner',
        ),
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.ManyToManyField(to='first_app.Person'),
        ),
    ]
