# Generated by Django 3.1.7 on 2021-04-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0008_auto_20210403_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personsprofile',
            name='phone_no',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
