# Generated by Django 3.1.7 on 2021-05-08 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0009_auto_20210418_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personsprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='first_app.person'),
        ),
    ]
