# Generated by Django 3.1.7 on 2021-06-14 16:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('keyvalue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyvalue',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 14, 16, 42, 15, 74326, tzinfo=utc)),
        ),
    ]
